### ISSUE TITLE
change layout of input date in afFieldGroup and afQuickField

### ISSUE THREAD

**Issue by jholl** [djhi/meteor-autoform-materialize#46]
similiar to #43 , the layout for date fields with label is different than text inputs; therefore needs different template when using afFieldGroup and afQuickField (looks like label and input should not be wrapped in `.input-field`)

**Comment by djhi** [comment]
Though you're right about the layout, I don't see any problems with the current implementation. On the playground, the date field is displayed correctly and its label behave correctly. 

I added an afQuickField version on the playground (will be deployed today), and could not see any issue.

Can you explain what the problem is and create a meteorpad for it ?

**Comment by 0o-de-lally** [comment]
Possibly related: I'm getting overlaying labels over input field only on date fields. Only 'pickadate' fields are doing this. Is there some way I can fix this?

Using: 
gildaspk:autoform-materialize         0.0.26

![screen shot 2016-03-18 at 9 00 11 am](https://cloud.githubusercontent.com/assets/1364012/13878461/f912ef84-ece7-11e5-9fd5-e4824a18deef.png)
