### ISSUE TITLE
select-radio-inline not showing

### ISSUE THREAD

**Issue by andfs** [djhi/meteor-autoform-materialize#91]
When I choose a Boolean field with type select-radio-inline nothing is shown

```
situacaoConveniado:{
    type: Boolean,
        autoform: {
            label: "Situação",
            type: "select-radio-inline",
            trueLabel: "Ativo",
            falseLabel: "Inativo",
            value: true
        }
  }
```

**Comment by hartreed** [comment]
Just ran into this issue myself, it appears that my issue is that the poetic:materialize-scss package styles the radio elements to shift them -9999px offscreen (and puts them at 0 opacity).

I assume this is because it's supposed to be replacing the default element with a custom styled one, but autoform-materialize doesn't seem to be doing this.

There seem to be several conflicts between the default materialize styling and this package, I also had to override the select element style to even get them to show up.

@djhi Could you comment on this? Am I missing something obvious about the materialize config? Is there a particular autoform select element that you recommend that is properly styled?

@andfs If you haven't already tried this, the 'switch' element ought to fit this particular use case.

**Comment by DanceParty** [comment]
Adding this to the CSS will fix this issue (at least in my case)

```
input[type="radio" i] {
  position: static !important;
  left: 0px !important;
  opacity: 100 !important;
}
```

**Comment by djhi** [comment]
I no longer use Meteor and won't be updating this project anymore. If anyone is interested in taking care of it, I'll gladly transfer ownership.

**Comment by djhi** [comment]
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).
